### ISSUE TITLE
Drivers reporting no file descriptors available

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/core#67] opened 2020-12-15 03:42 UTC
Intermittently all drivers will stop responding to method requests (message=core execute request failed) and starts to log the following error
```
level=ERROR time=2020-12-15T03:00:53Z source=http.server message=Error while connecting a new socket
2020-12-15T11:00:53.838+08:00	accept: No file descriptors available (Socket::Error)
2020-12-15T11:00:53.838+08:00	from ../usr/share/crystal/src/socket.cr:274:11 in 'accept_impl'
2020-12-15T11:00:53.838+08:00	from ../usr/share/crystal/src/socket/tcp_server.cr:107:20 in 'accept?'
2020-12-15T11:00:53.838+08:00	from ../usr/share/crystal/src/http/server.cr:459:13 in '->'
2020-12-15T11:00:53.838+08:00	from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'
2020-12-15T11:00:53.838+08:00	from ../usr/share/crystal/src/fiber.cr:92:34 in '->'
2020-12-15T11:00:53.838+08:00	from ???
```

Restarting `core` resolves.
Appears to happen more often as the number of running modules increases.

**Comment by stakach** [comment] 2021-03-10 05:36
this should be occurring less if not resolved with https://github.com/PlaceOS/driver/commit/e902a0fa4ae0f2d6a0ec865f06d0f50e7d92a0e6

however it still seems like an issue with the containers limits
@PhilPearson can you confirm what environment this is occurring in? Fargate, K8s, development etc
@w-le can you double check that descriptor limits are high on the dev env
@OllieMoylette can you ensure the limits on fargate for core are say 65536 - the default is 1024
https://ecs-fargate-dev-ops-data.workshop.aws/dev/lab6.html#ulimits

**Comment by w-le** [comment] 2021-03-10 06:15
Ok I've edited the partner-environment docker-compose config to set the max open file descriptors to 40000 instead of the default (which is often 1024 per process): 
https://github.com/place-labs/partner-environment/commit/c4777f68ad0095476c29ecf904ea06fe25589886

Note that this can't have any effect on the host's hard limit on max file descriptors, which is still enforced inside docker containers. So (assuming that the issue is related to exceeding max file descriptors) if the issue persists following this docker-compose.yml change then a host ulimit change may be required to increase the hard limit: https://stackoverflow.com/a/50145392

**Comment by PhilPearson** [comment] 2021-03-10 08:51
@stakach, this was occurring in a Fargate deployment.

**Comment by OllieMoylette** [comment] 2021-03-15 11:50
So I have added and tested in our fargate deployment - it looks good to add to the Woodside deployment. The following can be added to the 'ContainerDefinitions' section of the cloudformation of core and rest-api....

```
Ulimits:
 - Name: nofile
    HardLimit: 40000
    SoftLimit: 40000
```
 Can you pass this on @PhilPearson - not sure who is the Woodside contact now that Andi has moved on?

**Comment by stakach** [comment] 2021-03-17 03:52
OK this should be resolved now with https://github.com/PlaceOS/deploy-aws/commit/60bf136ef91e81d49f81565a21c71c8943321d08 in place

@w-le any changes required on the K8s side? Forgot to mention that above

**Closed** 2021-03-22 01:18 UTC
Labels: focus: backend, focus: devops, priority: high
